name: CI

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-20.04
    env:
      MIX_env: dev
      MIX_TARGET: rpi
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: "24"
          elixir-version: "1.12"

      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - run: mix archive.install hex nerves_bootstrap --force
      - run: mix deps.get --only dev
      - run: mix firmware